spring:
  application:
    name: judge-v2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/judge-v2?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=Europe/Sofia
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: true
  sql:
    init:
      mode: never
  mvc:
    hidden method:
      filter:
        enabled: true
  thymeleaf:
    prefix: file:./src/main/resources/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    cache: false
  web:
    resources:
      cache:
        period: 0
      static-locations: file:./src/main/resources/static/
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
server:
  port: 8080
